export {default as Dashboard} from './Dashboard.vue'
export {default as Users} from './Users.vue'
export {default as Orders} from './Orders.vue'
export {default as Deals} from './Deals.vue'
export {default as Products} from './Products.vue'
export {default as Profile} from './UserProfile.vue'